[2024-02-28T16:49:04.401+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rick_and_morty_etl.dbt_run manual__2024-02-28T15:42:23.644193+00:00 [queued]>
[2024-02-28T16:49:04.408+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rick_and_morty_etl.dbt_run manual__2024-02-28T15:42:23.644193+00:00 [queued]>
[2024-02-28T16:49:04.409+0000] {taskinstance.py:2193} INFO - Starting attempt 13 of 14
[2024-02-28T16:49:04.419+0000] {taskinstance.py:2214} INFO - Executing <Task(DockerOperator): dbt_run> on 2024-02-28 15:42:23.644193+00:00
[2024-02-28T16:49:04.431+0000] {standard_task_runner.py:60} INFO - Started process 2392 to run task
[2024-02-28T16:49:04.434+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'rick_and_morty_etl', 'dbt_run', 'manual__2024-02-28T15:42:23.644193+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/rick_and_morty_etl.py', '--cfg-path', '/tmp/tmprtj4m98l']
[2024-02-28T16:49:04.435+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask dbt_run
[2024-02-28T16:49:04.490+0000] {task_command.py:423} INFO - Running <TaskInstance: rick_and_morty_etl.dbt_run manual__2024-02-28T15:42:23.644193+00:00 [running]> on host f633dc85971f
[2024-02-28T16:49:04.581+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='raft_airflow' AIRFLOW_CTX_DAG_ID='rick_and_morty_etl' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T15:42:23.644193+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T15:42:23.644193+00:00'
[2024-02-28T16:49:04.688+0000] {docker.py:359} INFO - Starting docker container from image raft_airflow-dbt_tool
[2024-02-28T16:49:12.007+0000] {docker.py:429} INFO - [0m16:49:11  Running with dbt=1.7.8
[2024-02-28T16:49:12.584+0000] {docker.py:429} INFO - [0m16:49:12  Registered adapter: postgres=1.7.8
[2024-02-28T16:49:12.607+0000] {docker.py:429} INFO - [0m16:49:12  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-02-28T16:49:14.192+0000] {docker.py:429} INFO - [0m16:49:14  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.dbt_tool.example
[2024-02-28T16:49:14.228+0000] {docker.py:429} INFO - [0m16:49:14  Found 1 model, 2 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2024-02-28T16:49:14.233+0000] {docker.py:429} INFO - [0m16:49:14
[2024-02-28T16:49:14.445+0000] {docker.py:429} INFO - [0m16:49:14  Concurrency: 1 threads (target='dev')
[2024-02-28T16:49:14.447+0000] {docker.py:429} INFO - [0m16:49:14
[2024-02-28T16:49:14.470+0000] {docker.py:429} INFO - [0m16:49:14  1 of 1 START sql view model rick_and_morty.location_character_merge ............ [RUN]
[2024-02-28T16:49:14.624+0000] {docker.py:429} INFO - [0m16:49:14  1 of 1 OK created sql view model rick_and_morty.location_character_merge ....... [[32mCREATE VIEW[0m in 0.15s]
[2024-02-28T16:49:14.710+0000] {docker.py:429} INFO - [0m16:49:14
[2024-02-28T16:49:14.715+0000] {docker.py:429} INFO - [0m16:49:14  Finished running 1 view model in 0 hours 0 minutes and 0.47 seconds (0.47s).
[2024-02-28T16:49:14.748+0000] {docker.py:429} INFO - [0m16:49:14
[2024-02-28T16:49:14.750+0000] {docker.py:429} INFO - [0m16:49:14  [32mCompleted successfully[0m
[2024-02-28T16:49:14.754+0000] {docker.py:429} INFO - [0m16:49:14
[2024-02-28T16:49:14.760+0000] {docker.py:429} INFO - [0m16:49:14  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-02-28T16:49:15.867+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=rick_and_morty_etl, task_id=dbt_run, execution_date=20240228T154223, start_date=20240228T164904, end_date=20240228T164915
[2024-02-28T16:49:15.971+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-28T16:49:16.267+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
